//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHDS.Entities.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeRecords
    {
        public int id { get; set; }
        public Nullable<int> clock_id { get; set; }
        public string emp_id { get; set; }
        public string card_id { get; set; }
        public System.DateTime sign_time { get; set; }
        public Nullable<byte> mark { get; set; }
        public Nullable<byte> flag { get; set; }
        public string bill_id { get; set; }
        public string EventName { get; set; }
        public Nullable<int> Pos_sequ { get; set; }
        public Nullable<System.DateTime> dCollectTime { get; set; }
    }
}
