//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHDS.Entities.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_发货_汇总_销售与加工
    {
        public int 年 { get; set; }
        public int 月 { get; set; }
        public decimal 销售金额 { get; set; }
        public decimal 销售面积 { get; set; }
        public decimal 加工金额 { get; set; }
        public decimal 加工面积 { get; set; }
    }
}
