//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHDS.Entities.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class 业务类型
    {
        public string MvP { get; set; }
        public string 业务类型1 { get; set; }
        public string 类型描述 { get; set; }
        public string 性质 { get; set; }
        public Nullable<int> 库存计算 { get; set; }
        public string 状态 { get; set; }
        public string ExcelServerRCID { get; set; }
        public Nullable<int> ExcelServerRN { get; set; }
        public Nullable<int> ExcelServerCN { get; set; }
        public string ExcelServerRC1 { get; set; }
        public string ExcelServerWIID { get; set; }
        public string ExcelServerRTID { get; set; }
        public Nullable<int> ExcelServerCHG { get; set; }
        public Nullable<int> 业务计算 { get; set; }
        public Nullable<int> 对账计算 { get; set; }
    }
}
