//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHDS.Entities.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class 发货
    {
        public string 客户 { get; set; }
        public string 送货单号 { get; set; }
        public string 地址 { get; set; }
        public Nullable<System.DateTime> 送货日期 { get; set; }
        public string 备注 { get; set; }
        public string 客户编号 { get; set; }
        public string ExcelServerRCID { get; set; }
        public Nullable<int> ExcelServerRN { get; set; }
        public Nullable<int> ExcelServerCN { get; set; }
        public string ExcelServerRC1 { get; set; }
        public string ExcelServerWIID { get; set; }
        public string ExcelServerRTID { get; set; }
        public Nullable<int> ExcelServerCHG { get; set; }
        public string 业务类型 { get; set; }
        public string 业务描述 { get; set; }
        public string 冲销理由 { get; set; }
        public string 创建者 { get; set; }
    }
}
