//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHDS.Entities.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class 生产入库_D
    {
        public string 型号 { get; set; }
        public string 描述 { get; set; }
        public Nullable<decimal> 长 { get; set; }
        public Nullable<decimal> 宽 { get; set; }
        public Nullable<int> 片数 { get; set; }
        public Nullable<decimal> 平方数 { get; set; }
        public string ExcelServerRCID { get; set; }
        public Nullable<int> ExcelServerRN { get; set; }
        public Nullable<int> ExcelServerCN { get; set; }
        public string ExcelServerRC1 { get; set; }
        public string ExcelServerWIID { get; set; }
        public string ExcelServerRTID { get; set; }
        public Nullable<int> ExcelServerCHG { get; set; }
        public int 自增 { get; set; }
    }
}
