//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHDS.Entities.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class 考勤明细
    {
        public string 人员编号 { get; set; }
        public string 姓名 { get; set; }
        public System.DateTime 日期 { get; set; }
        public Nullable<decimal> 正常出勤 { get; set; }
        public Nullable<decimal> 加班 { get; set; }
        public string 上班1 { get; set; }
        public string 下班1 { get; set; }
        public string 上班2 { get; set; }
        public string 下班2 { get; set; }
        public string 上班3 { get; set; }
        public string 下班3 { get; set; }
        public string ExcelServerRCID { get; set; }
        public Nullable<int> ExcelServerRN { get; set; }
        public Nullable<int> ExcelServerCN { get; set; }
        public string ExcelServerRC1 { get; set; }
        public string ExcelServerWIID { get; set; }
        public string ExcelServerRTID { get; set; }
        public Nullable<int> ExcelServerCHG { get; set; }
        public string 状态 { get; set; }
        public Nullable<int> 当日工龄 { get; set; }
        public Nullable<int> 上月工龄 { get; set; }
        public Nullable<System.DateTime> 首打日期 { get; set; }
    }
}
