//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHDS.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class 发货_DETAIL
    {
        public string 编号 { get; set; }
        public string 代号 { get; set; }
        public string 规格 { get; set; }
        public string 工艺 { get; set; }
        public string 木种 { get; set; }
        public string 计价单位 { get; set; }
        public Nullable<decimal> PCS { get; set; }
        public Nullable<decimal> 单价 { get; set; }
        public Nullable<decimal> 金额 { get; set; }
        public string 描述 { get; set; }
        public string ExcelServerRCID { get; set; }
        public Nullable<int> ExcelServerRN { get; set; }
        public Nullable<int> ExcelServerCN { get; set; }
        public string ExcelServerRC1 { get; set; }
        public string ExcelServerWIID { get; set; }
        public string ExcelServerRTID { get; set; }
        public Nullable<int> ExcelServerCHG { get; set; }
        public string 类型 { get; set; }
        public Nullable<decimal> 单位数量 { get; set; }
        public string 标记 { get; set; }
        public int PK { get; set; }
    }
}
