//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHDS.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class 打卡登记
    {
        public string 签卡原因 { get; set; }
        public string 人员编号 { get; set; }
        public string 姓名 { get; set; }
        public Nullable<System.DateTime> 时间 { get; set; }
        public Nullable<System.DateTime> 审核时间 { get; set; }
        public string ExcelServerRCID { get; set; }
        public Nullable<int> ExcelServerRN { get; set; }
        public Nullable<int> ExcelServerCN { get; set; }
        public string ExcelServerRC1 { get; set; }
        public string ExcelServerWIID { get; set; }
        public string ExcelServerRTID { get; set; }
        public Nullable<int> ExcelServerCHG { get; set; }
        public string 审核状态 { get; set; }
        public string 审核人 { get; set; }
        public int pk { get; set; }
    }
}
