//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QyWeixin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ES_RepCase
    {
        public string rcId { get; set; }
        public string RtId { get; set; }
        public Nullable<int> fillDept { get; set; }
        public string fillDeptName { get; set; }
        public Nullable<int> fillUser { get; set; }
        public string fillUserName { get; set; }
        public System.DateTime fillDate { get; set; }
        public string rcDesc { get; set; }
        public Nullable<short> state { get; set; }
        public int lstFiller { get; set; }
        public string lstFillerName { get; set; }
        public System.DateTime lstFillDate { get; set; }
        public short backUpdate { get; set; }
        public short openState { get; set; }
        public Nullable<int> openBy { get; set; }
        public string openByName { get; set; }
        public string OpenBySesId { get; set; }
        public short lockState { get; set; }
        public short lockInServer { get; set; }
        public short noticeState { get; set; }
        public short setNStateInServer { get; set; }
        public Nullable<int> replacerId_fill { get; set; }
        public string replacerName_fill { get; set; }
        public Nullable<int> replacerId_lstFill { get; set; }
        public string replacerName_lstFill { get; set; }
        public Nullable<System.DateTime> printTime { get; set; }
        public string wiId { get; set; }
        public short commitByDataWriter { get; set; }
    }
}
