//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QyWeixin
{
    using System;
    using System.Collections.Generic;
    
    public partial class 人员档案
    {
        public string 人员编号 { get; set; }
        public Nullable<System.DateTime> 登记时间 { get; set; }
        public string 姓名 { get; set; }
        public string 状态 { get; set; }
        public string 性别 { get; set; }
        public string 证件号码 { get; set; }
        public Nullable<System.DateTime> 出生年月 { get; set; }
        public string 联系电话 { get; set; }
        public string 联系地址 { get; set; }
        public Nullable<System.DateTime> 离职时间 { get; set; }
        public string ExcelServerRCID { get; set; }
        public Nullable<int> ExcelServerRN { get; set; }
        public Nullable<int> ExcelServerCN { get; set; }
        public string ExcelServerRC1 { get; set; }
        public string ExcelServerWIID { get; set; }
        public string ExcelServerRTID { get; set; }
        public Nullable<int> ExcelServerCHG { get; set; }
        public Nullable<System.DateTime> 入职时间 { get; set; }
        public string 考勤班次 { get; set; }
    }
}
