//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHDS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class 物料登记
    {
        public string 状态 { get; set; }
        public string 编号 { get; set; }
        public string 类型 { get; set; }
        public string 描述 { get; set; }
        public string 型号 { get; set; }
        public string 规格 { get; set; }
        public string 工艺 { get; set; }
        public string 木种 { get; set; }
        public string 木种个数 { get; set; }
        public string 图形编号 { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public string 分类编号 { get; set; }
        public string ExcelServerRCID { get; set; }
        public Nullable<int> ExcelServerRN { get; set; }
        public Nullable<int> ExcelServerCN { get; set; }
        public string ExcelServerRC1 { get; set; }
        public string ExcelServerWIID { get; set; }
        public string ExcelServerRTID { get; set; }
        public Nullable<int> ExcelServerCHG { get; set; }
        public Nullable<decimal> 面皮厚度 { get; set; }
    }
}
