//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHDS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class 考勤卡号变动
    {
        public string 状态 { get; set; }
        public string 卡号 { get; set; }
        public Nullable<System.DateTime> 起始日期 { get; set; }
        public string ExcelServerRCID { get; set; }
        public Nullable<int> ExcelServerRN { get; set; }
        public Nullable<int> ExcelServerCN { get; set; }
        public string ExcelServerRC1 { get; set; }
        public string ExcelServerWIID { get; set; }
        public string ExcelServerRTID { get; set; }
        public Nullable<int> ExcelServerCHG { get; set; }
        public Nullable<System.DateTime> 截止日期 { get; set; }
        public int pk { get; set; }
    }
}
