//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QyWeixin.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ES_Tmp
    {
        public string RtId { get; set; }
        public string RtNo { get; set; }
        public string RtName { get; set; }
        public short State { get; set; }
        public Nullable<int> ClassId { get; set; }
        public System.DateTime CreTime { get; set; }
        public Nullable<int> CreUid { get; set; }
        public string CreUname { get; set; }
        public System.DateTime UpdTime { get; set; }
        public Nullable<int> UpdUid { get; set; }
        public string UpdUname { get; set; }
        public short QryOnly { get; set; }
        public short IfCheckout { get; set; }
        public Nullable<int> CheckoutBy { get; set; }
        public string CheckoutByName { get; set; }
        public short ProtectType { get; set; }
        public string RtPwd { get; set; }
        public short IfLockByExp { get; set; }
        public string LockExpText { get; set; }
        public string LockExpSpec { get; set; }
        public short LockDependDate { get; set; }
        public short ifMakeWeb { get; set; }
        public int ver { get; set; }
        public short indexType { get; set; }
        public string indexDesc { get; set; }
        public string indexSpec { get; set; }
        public short hasNoticeExp { get; set; }
        public short fileFormat { get; set; }
    }
}
