//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QyWeixin.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class 往来单位
    {
        public string 单位编号 { get; set; }
        public string 单位名称 { get; set; }
        public string 电话 { get; set; }
        public string 传真 { get; set; }
        public string 单位地址 { get; set; }
        public Nullable<System.DateTime> 登记日期 { get; set; }
        public string ExcelServerRCID { get; set; }
        public Nullable<int> ExcelServerRN { get; set; }
        public Nullable<int> ExcelServerCN { get; set; }
        public string ExcelServerRC1 { get; set; }
        public string ExcelServerWIID { get; set; }
        public string ExcelServerRTID { get; set; }
        public Nullable<int> ExcelServerCHG { get; set; }
        public string 单位类型 { get; set; }
        public string 单位性质 { get; set; }
        public Nullable<int> RANK { get; set; }
    }
}
